name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install
        run: make docker-install-ci
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make docker-test
